version: '3'
services:
  tomcat:
    environment:
      - CATALINA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=5005,suspend=n,server=y
    image: jongsx/tomcat:8.0.36
    platform: linux/x86_64
    ports:
      - 8080:8080
      - 10001:10001
      - 10002:10002
      - 5005:5005