version: '3'
services:
  confluence:
    image: atlassian/confluence-server:6.12.0
    ports:
      - "8090:8090"
      - "5005:5005"
    environment:
      - JVM_SUPPORT_RECOMMENDED_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
    depends_on:
      - postgres
  postgres:
    image: postgres:10.7-alpine
    environment: 
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=confluence