version: '3.0'
services:
  salt:
    image: saltstack/salt:3000
    container_name: salt
    ports:
      - 8000:8000
      - 4505:4505
      - 4506:4506
    environment:
      - SALT_SHARE_SECRET=password
    hostname: salt