version: '3'
services:
  joomla:
    image: jongsx/joomla:3.7.5
    links:
      - mysql:joomla
    depends_on:
      - mysql
      - openldap
    environment: 
      - JOOMLA_DB_HOST=mysql:3306
      - JOOMLA_DB_USER=root
      - JOOMLA_DB_PASSWORD=root
      - JOOMLA_DB_NAME=joomla
    ports:
      - "8080:80"

  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
  
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2

