version: '3'
services:
 web:
   platform: linux/x86_64
   image: vulhub/joomla:3.4.5
   depends_on:
    - mysql
   environment: 
    - JOOMLA_DB_HOST=mysql:3306
    - JOOMLA_DB_USER=root
    - JOOMLA_DB_PASSWORD=root
    - JOOMLA_DB_NAME=joomla
   ports:
    - "8080:80"
 mysql:
   platform: linux/x86_64
   image: mysql:5
   ports:
    - "3306:3306"
   environment: 
    - MYSQL_ROOT_PASSWORD=root
